name: first workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello, world!"
      - name: "using secrets"
        run: |
          echo "username: ${{ secrets.QA_USERNAME}}"
          echo "password: ${{ secrets.QA_PASSWORD}}"
